-- Big, dense, single-column bigint key: this is what makes range elision work
-- (the planner can refute a BETWEEN predicate that lands in a cached range).
CREATE TABLE IF NOT EXISTS products (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku         text        NOT NULL,
  name        text        NOT NULL,
  category    text        NOT NULL,
  price_cents integer     NOT NULL,
  attrs       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Trigram GIN index → fuzzy ILIKE search, federated through the clone until warmed.
CREATE INDEX IF NOT EXISTS products_name_trgm ON products USING gin (name gin_trgm_ops);

-- total_cents is a STORED generated column: writing an order on the clone goes
-- through the overlay's copy-on-write path and must recompute it locally.
CREATE TABLE IF NOT EXISTS orders (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  bigint      NOT NULL,
  qty         integer     NOT NULL,
  unit_cents  integer     NOT NULL,
  total_cents integer GENERATED ALWAYS AS (unit_cents * qty) STORED,
  origin      text        NOT NULL DEFAULT 'source',
  created_at  timestamptz NOT NULL DEFAULT now()
);
