#!/usr/bin/env bash
# =============================================================================
# tpch_validate.sh -- validate the gfs lazy clone against a MULTI-TABLE workload
# (TPC-H) at a chosen scale. Proves the router on real joins/aggregates:
#   P1 range-hydrate (l_orderkey BETWEEN), P2 partial-selective (l_quantity=v on
#   the too-big lineitem), P3 federate (multi-table joins/aggregates pushed to the
#   source via postgres_fdw -- exercises the recursive RTE swap), asserting
#   clone == source for every query.
#
# SOURCE IS PERSISTENT: TPC-H data is generated by DuckDB and loaded ONCE into a
# postgres:16 container backed by a NAMED DOCKER VOLUME (per scale factor). Reruns
# REUSE it -- no regeneration. Only the (lazy, cheap) CLONE is rebuilt each run.
#
#   SF=1 ./tpch_validate.sh           # build source once (if absent), then validate
#   SF=1 ./tpch_validate.sh           # again -> reuses the source, just re-clones
#   SF=50 ./tpch_validate.sh          # a different scale -> its own volume
#   REBUILD_SOURCE=1 SF=1 ./tpch_validate.sh   # force regenerate the source
#   DROP_SOURCE=1 SF=1 ./tpch_validate.sh      # delete the source container+volume
# =============================================================================
set -uo pipefail

SF="${SF:-1}"
SFTAG="${SF//./p}"
SRC_PORT="${SRC_PORT:-55610}"
CLONE_PORT="${CLONE_PORT:-55611}"
SRC_NAME="gfs-tpch-src-sf${SFTAG}"     # persistent, per scale factor
SRC_VOL="gfs-tpch-vol-sf${SFTAG}"      # named volume holds PGDATA across runs
CLONE_DIR="$(mktemp -d)/clone"
GFS_IMAGE="${GFS_IMAGE:-gfs-postgres:16}"
GFS_BIN="${GFS_BIN:-$(cd "$(dirname "$0")/../../.." && pwd)/target/debug/gfs}"
PSQL="${PSQL:-/opt/homebrew/opt/postgresql@16/bin/psql}"
DATA_DIR="${DATA_DIR:-/tmp/gfs-tpch-data-sf${SFTAG}}"

red()  { printf '\033[31m%s\033[0m' "$1"; }
grn()  { printf '\033[32m%s\033[0m' "$1"; }
note() { printf '\n\033[1;36m== %s ==\033[0m\n' "$1"; }
PASS=0; FAIL=0

src() { PGPASSWORD=pw "$PSQL" "postgresql://app:pw@localhost:${SRC_PORT}/tpch" -tAqc "$1" 2>/dev/null; }
cln() { PGPASSWORD=postgres "$PSQL" "postgresql://postgres:postgres@localhost:${CLONE_PORT}/postgres" -tAqc "$1" 2>/dev/null; }
ck()  { echo "SELECT COALESCE(md5(string_agg(t::text,'|' ORDER BY t::text)),'NONE') FROM ($1) t"; }
counters() { cln "SELECT COALESCE(sum(rows_fetched),0)||' '||COALESCE(sum(federate_calls),0) FROM gfs.clones"; }
pulled()   { cln "SELECT COALESCE(sum(rows_fetched),0) FROM gfs.clones"; }

# Teardown removes ONLY the ephemeral clone -- the source container+volume PERSIST.
cleanup() {
  local c; c="$(docker ps -aq --filter "publish=${CLONE_PORT}")"
  [[ -n "$c" ]] && docker rm -f "$c" >/dev/null 2>&1 || true
  rm -rf "$(dirname "$CLONE_DIR")" 2>/dev/null || true
}
trap cleanup EXIT

[[ -x "$GFS_BIN" ]] || { red "gfs binary not found at $GFS_BIN\n"; exit 1; }

src_up()       { docker ps --format '{{.Names}}' | grep -qx "$SRC_NAME"; }
src_has_data() { [[ "$(src 'SELECT count(*) FROM lineitem' 2>/dev/null || echo 0)" -gt 0 ]]; }

build_source() {
  echo "  generating TPC-H SF=$SF (DuckDB) -> $DATA_DIR ..."
  rm -rf "$DATA_DIR"; mkdir -p "$DATA_DIR"
  duckdb -c "INSTALL tpch; LOAD tpch; CALL dbgen(sf=${SF});
$(for t in region nation supplier part partsupp customer orders lineitem; do
    echo "COPY ${t} TO '${DATA_DIR}/${t}.csv' (FORMAT csv, HEADER false);"; done)" >/dev/null 2>&1 \
    || { red "duckdb generation failed\n"; exit 1; }
  echo "  generated lineitem rows=$(wc -l < "${DATA_DIR}/lineitem.csv" | tr -d ' ')"
  # Canonical TPC-H DDL WITH PRIMARY KEYS -- the clone bootstrap registers a table
  # as a clone only if it has a unique index; no PK -> no registration.
  src "
CREATE TABLE region   (r_regionkey int PRIMARY KEY, r_name char(25), r_comment varchar(152));
CREATE TABLE nation   (n_nationkey int PRIMARY KEY, n_name char(25), n_regionkey int, n_comment varchar(152));
CREATE TABLE supplier (s_suppkey int PRIMARY KEY, s_name char(25), s_address varchar(40), s_nationkey int, s_phone char(15), s_acctbal numeric(15,2), s_comment varchar(101));
CREATE TABLE part     (p_partkey int PRIMARY KEY, p_name varchar(55), p_mfgr char(25), p_brand char(10), p_type varchar(25), p_size int, p_container char(10), p_retailprice numeric(15,2), p_comment varchar(23));
CREATE TABLE partsupp (ps_partkey int, ps_suppkey int, ps_availqty int, ps_supplycost numeric(15,2), ps_comment varchar(199), PRIMARY KEY(ps_partkey, ps_suppkey));
CREATE TABLE customer (c_custkey int PRIMARY KEY, c_name varchar(25), c_address varchar(40), c_nationkey int, c_phone char(15), c_acctbal numeric(15,2), c_mktsegment char(10), c_comment varchar(117));
CREATE TABLE orders   (o_orderkey int PRIMARY KEY, o_custkey int, o_orderstatus char(1), o_totalprice numeric(15,2), o_orderdate date, o_orderpriority char(15), o_clerk char(15), o_shippriority int, o_comment varchar(79));
CREATE TABLE lineitem (l_orderkey int, l_partkey int, l_suppkey int, l_linenumber int, l_quantity numeric(15,2), l_extendedprice numeric(15,2), l_discount numeric(15,2), l_tax numeric(15,2), l_returnflag char(1), l_linestatus char(1), l_shipdate date, l_commitdate date, l_receiptdate date, l_shipinstruct char(25), l_shipmode char(10), l_comment varchar(44), PRIMARY KEY(l_orderkey, l_linenumber));
" >/dev/null
  echo "  loading into source..."
  for t in region nation supplier part partsupp customer orders lineitem; do
    PGPASSWORD=pw "$PSQL" "postgresql://app:pw@localhost:${SRC_PORT}/tpch" -qc "\copy ${t} FROM '${DATA_DIR}/${t}.csv' CSV" >/dev/null 2>&1 \
      || { red "load $t failed\n"; exit 1; }
  done
  src "ANALYZE" >/dev/null   # REQUIRED: cost model reads source reltuples/width via remote estimate
  rm -rf "$DATA_DIR"          # CSVs no longer needed (data is in the volume)
}

ensure_source() {
  if [[ "${DROP_SOURCE:-0}" == 1 ]]; then
    docker rm -f "$SRC_NAME" >/dev/null 2>&1; docker volume rm "$SRC_VOL" >/dev/null 2>&1
    echo "dropped source container $SRC_NAME + volume $SRC_VOL"; trap - EXIT; exit 0
  fi
  if [[ "${REBUILD_SOURCE:-0}" == 1 ]]; then
    docker rm -f "$SRC_NAME" >/dev/null 2>&1; docker volume rm "$SRC_VOL" >/dev/null 2>&1
  fi
  # free the port: stop any OTHER tpch source (its volume persists)
  for c in $(docker ps --filter "publish=${SRC_PORT}" --format '{{.Names}}' | grep '^gfs-tpch-src-' | grep -vx "$SRC_NAME"); do
    docker stop "$c" >/dev/null 2>&1 || true
  done
  # (Re)create the container on its persistent volume WITH analytical tuning. The
  # volume holds the data, so recreating the container is cheap (seconds) and lets
  # us apply config -- the default postgres:16 work_mem/shared_buffers are far too
  # small for the federated multi-table joins (a 6-table join over 60M rows spills
  # and crawls). Data survives in $SRC_VOL.
  docker rm -f "$SRC_NAME" >/dev/null 2>&1 || true
  docker run -d --name "$SRC_NAME" --shm-size=2g \
    -e POSTGRES_PASSWORD=pw -e POSTGRES_USER=app -e POSTGRES_DB=tpch \
    -v "${SRC_VOL}:/var/lib/postgresql/data" -p "${SRC_PORT}:5432" postgres:16 \
    -c shared_buffers=2GB -c work_mem=512MB -c effective_cache_size=6GB \
    -c max_parallel_workers_per_gather=4 -c max_parallel_workers=8 -c jit=off >/dev/null
  for i in $(seq 1 90); do docker exec "$SRC_NAME" pg_isready -U app -d tpch >/dev/null 2>&1 && break; sleep 1; done
  if src_has_data; then
    echo "  REUSING persistent source $SRC_NAME (lineitem=$(src 'SELECT count(*) FROM lineitem'), $(src "SELECT pg_size_pretty(pg_database_size('tpch'))")) -- no rebuild"
  else
    echo "  building source ONCE (persists in volume $SRC_VOL; reused next runs)..."
    build_source
  fi
}

# ---------------------------------------------------------------------------
note "Source (persistent, SF=$SF)"
ensure_source
echo "  source ready: lineitem=$(src 'SELECT count(*) FROM lineitem')  orders=$(src 'SELECT count(*) FROM orders')  size=$(src "SELECT pg_size_pretty(pg_database_size('tpch'))")"

# ---------------------------------------------------------------------------
note "Clone (ephemeral -- lazy, rebuilt each run)"
"$GFS_BIN" clone --from "postgresql://app:pw@host.docker.internal:${SRC_PORT}/tpch" \
  --image "$GFS_IMAGE" --port "$CLONE_PORT" "$CLONE_DIR" >/dev/null 2>&1
cln "SELECT 1" >/dev/null || { red "clone unreachable\n"; exit 1; }
nclones="$(cln "SELECT count(*) FROM gfs.clones")"
echo "  registered clones: $nclones (expect 8)"
[[ "$nclones" == "8" ]] && { PASS=$((PASS+1)); echo "  $(grn PASS) all 8 TPC-H tables registered"; } \
  || { FAIL=$((FAIL+1)); echo "  $(red FAIL) only $nclones registered (PK missing on source?)"; }

# Pin weights; horizon=0 stops amortization-to-own so routes are stable. NOT
# calibrated (calibrate would shrink net -> facts become ownable -> P2 collapses).
cln "UPDATE gfs.cost SET net=1, source=20, negligible=100000, horizon=0, partial_max_frac=0.05" >/dev/null
# Ceiling SCALED to the data (SF-independent): 0.1 * lineitem whole-own cost. Then
# the big facts stay NOT-whole-ownable (whole=10x > ceiling) while a partial_max_frac
# (5%) slice fits (0.05*whole < 0.1*whole=ceiling) -> P2 fires at any scale; small
# dims (customer/part/...) stay whole-ownable. A fixed ceiling does NOT generalize
# across scales (caught by the P2 route assertion at SF10).
LIW="$(cln "SELECT (x.net * s.row_bytes * s.source_rows)::bigint FROM gfs.clone_source s, gfs.cost x WHERE s.relid='lineitem'::regclass")"
CEIL=$(( ${LIW:-1000000000} / 10 ))
cln "UPDATE gfs.cost SET ceiling=$CEIL" >/dev/null
echo "  weights pinned (ceiling=$CEIL = 0.1*lineitem_whole($LIW) -> facts not-ownable, 5% slice fits; NOT calibrated)"

reset_clone() {
  cln "TRUNCATE region,nation,supplier,part,partsupp,customer,orders,lineitem;
       DELETE FROM gfs.cached; DELETE FROM gfs.cached_predicate;
       UPDATE gfs.clone_source SET whole_cached=false, access_count=0, partial_rows=0, no_partial=false;
       UPDATE gfs.clone_stats SET rows_fetched=0,fetch_calls=0,federate_calls=0;" >/dev/null
}
route_of() {
  local b a hyd fed; b="$(counters)"; cln "$1" >/dev/null 2>&1; a="$(counters)"
  local bf bd af ad; read -r bf bd <<<"$b"; read -r af ad <<<"$a"
  hyd=$((af-bf)); fed=$((ad-bd))
  if   [[ $hyd -gt 0 ]]; then echo fetched
  elif [[ $fed -gt 0 ]]; then echo federated
  else echo local; fi
}
assert_eq() {
  local cs ss; cs="$(cln "$(ck "$2")")"; ss="$(src "$(ck "$2")")"
  if [[ "$cs" == "$ss" && -n "$cs" && "$cs" != "NONE" ]]; then PASS=$((PASS+1)); echo "  $(grn PASS) $1 -- clone == source"
  else FAIL=$((FAIL+1)); echo "  $(red FAIL) $1 -- clone != source"; fi
}

# ---------------------------------------------------------------------------
note "P1 -- RANGE-hydrate on the integer key (l_orderkey BETWEEN), then elision"
reset_clone
LO=$(( $(src 'SELECT max(l_orderkey)/2') )); HI=$((LO+200))
P1Q="SELECT l_orderkey,l_partkey,l_quantity FROM lineitem WHERE l_orderkey BETWEEN $LO AND $HI"
r1="$(route_of "$P1Q")"; r2="$(route_of "$P1Q")"
echo "  route shot1->shot2: $r1 -> $r2   (pulled=$(pulled) rows, not the whole table)"
[[ "$r1" == fetched && "$r2" == local ]] && { PASS=$((PASS+1)); echo "  $(grn PASS) range fetched then elided (local)"; } || { FAIL=$((FAIL+1)); echo "  $(red FAIL) P1 route ($r1->$r2)"; }
assert_eq "P1 range" "$P1Q"

# ---------------------------------------------------------------------------
note "P2 -- partial-selective on the too-big lineitem (l_quantity=v ~2%), second-chance"
reset_clone
P2Q="SELECT l_orderkey,l_linenumber FROM lineitem WHERE l_quantity = 25"
r1="$(route_of "$P2Q")"; p1="$(pulled)"
r2="$(route_of "$P2Q")"; p2="$(pulled)"
r3="$(route_of "$P2Q")"
match="$(src "SELECT count(*) FROM ($P2Q) t")"; total="$(src 'SELECT count(*) FROM lineitem')"
echo "  routes: $r1 -> $r2 -> $r3   (expect federated -> fetched -> local)"
echo "  matching=$match of $total ($(( total>0 ? match*100/total : 0 ))%)  partial pulled=$((p2-p1)) rows (the slice)"
[[ "$r1" == federated && "$r2" == fetched && "$r3" == local ]] && { PASS=$((PASS+1)); echo "  $(grn PASS) second-chance -> partial-own slice -> local"; } || { FAIL=$((FAIL+1)); echo "  $(red FAIL) P2 routes ($r1->$r2->$r3)"; }
assert_eq "P2 selective" "$P2Q"

# ---------------------------------------------------------------------------
note "P3 -- FEDERATE multi-table joins/aggregates (exercises the recursive RTE swap)"
reset_clone
Q1="SELECT l_returnflag,l_linestatus,sum(l_quantity) sq,count(*) c FROM lineitem WHERE l_shipdate <= date '1998-09-01' GROUP BY l_returnflag,l_linestatus ORDER BY l_returnflag,l_linestatus"
echo "  Q1  (lineitem aggregate):   route=$(route_of "$Q1")"; assert_eq "Q1 aggregate" "$Q1"
Q3="SELECT l_orderkey,o_orderdate,round(sum(l_extendedprice*(1-l_discount))::numeric,2) rev FROM customer,orders,lineitem WHERE c_mktsegment='BUILDING' AND c_custkey=o_custkey AND l_orderkey=o_orderkey AND o_orderdate<date '1995-03-15' AND l_shipdate>date '1995-03-15' GROUP BY l_orderkey,o_orderdate ORDER BY rev DESC,l_orderkey LIMIT 10"
echo "  Q3  (3-table join):         route=$(route_of "$Q3")"; assert_eq "Q3 3-table join" "$Q3"
Q5="SELECT n_name,round(sum(l_extendedprice*(1-l_discount))::numeric,2) rev FROM customer,orders,lineitem,supplier,nation,region WHERE c_custkey=o_custkey AND l_orderkey=o_orderkey AND l_suppkey=s_suppkey AND c_nationkey=s_nationkey AND s_nationkey=n_nationkey AND n_regionkey=r_regionkey AND r_name='ASIA' AND o_orderdate>=date '1994-01-01' AND o_orderdate<date '1995-01-01' GROUP BY n_name ORDER BY rev DESC"
echo "  Q5  (6-table join):         route=$(route_of "$Q5")"; assert_eq "Q5 6-table join" "$Q5"
Q10="SELECT c_custkey,n_name,round(sum(l_extendedprice*(1-l_discount))::numeric,2) rev FROM customer,orders,lineitem,nation WHERE c_custkey=o_custkey AND l_orderkey=o_orderkey AND o_orderdate>=date '1993-10-01' AND o_orderdate<date '1994-01-01' AND l_returnflag='R' AND c_nationkey=n_nationkey GROUP BY c_custkey,n_name ORDER BY rev DESC,c_custkey LIMIT 20"
echo "  Q10 (4-table join):         route=$(route_of "$Q10")"; assert_eq "Q10 4-table join" "$Q10"

# ---------------------------------------------------------------------------
note "P5 -- TEMPORAL range-hydrate (re-register orders on the DATE key o_orderdate)"
OSRC="$(cln "SELECT source_ref FROM gfs.clone_source WHERE relid='orders'::regclass")"
cln "SELECT gfs.unregister_clone('orders'::regclass)" >/dev/null
cln "SELECT gfs.register_clone('orders'::regclass, '$OSRC', 'o_orderdate')" >/dev/null
echo "  orders re-registered on o_orderdate -> chunk_kind=$(cln "SELECT chunk_kind FROM gfs.clone_source WHERE relid='orders'::regclass")"
reset_clone
W1="SELECT o_orderkey FROM orders WHERE o_orderdate BETWEEN date '1994-01-01' AND date '1994-01-31' ORDER BY o_orderkey"
r1="$(route_of "$W1")"; r2="$(route_of "$W1")"
echo "  narrow window 1994-01 (shot1->shot2): $r1 -> $r2   (pulled=$(pulled) rows, not the table)"
[[ "$r1" == fetched && "$r2" == local ]] && { PASS=$((PASS+1)); echo "  $(grn PASS) time-range fetched then elided (local)"; } || { FAIL=$((FAIL+1)); echo "  $(red FAIL) P5 route ($r1->$r2)"; }
assert_eq "P5 time-range" "$W1"
SUB="SELECT o_orderkey FROM orders WHERE o_orderdate BETWEEN date '1994-01-10' AND date '1994-01-20' ORDER BY o_orderkey"
r3="$(route_of "$SUB")"
echo "  sub-window 1994-01-10..20: $r3   (expect local -- covered by the cached range)"
[[ "$r3" == local ]] && { PASS=$((PASS+1)); echo "  $(grn PASS) sub-window elided (range coverage, 0 source contact)"; } || { FAIL=$((FAIL+1)); echo "  $(red FAIL) sub-window ($r3)"; }
assert_eq "P5 sub-window" "$SUB"
WIDE="SELECT o_orderkey FROM orders WHERE o_orderdate BETWEEN date '1992-01-01' AND date '1998-12-31' ORDER BY o_orderkey LIMIT 100"
echo "  wide window 1992..1998: $(route_of "$WIDE")   (exceeds cap -> federate, bounded; correctness still holds)"
assert_eq "P5 wide window" "$WIDE"

# ---------------------------------------------------------------------------
note "Clone state"
cln "SELECT clone,whole_cached,no_partial,partial_rows,access_count,rows_fetched,federate_calls FROM gfs.clones ORDER BY clone" \
  | awk -F'|' 'BEGIN{printf "  %-10s %-6s %-5s %-9s %-7s %-9s %-6s\n","table","whole","noP","partRows","access","fetched","feder"}{printf "  %-10s %-6s %-5s %-9s %-7s %-9s %-6s\n",$1,$2,$3,$4,$5,$6,$7}'

note "Verdict"
echo "  $PASS passed, $FAIL failed"
echo "  source kept: $SRC_NAME on volume $SRC_VOL (:$SRC_PORT) -- rerun reuses it; DROP_SOURCE=1 SF=$SF to remove"
[[ $FAIL -eq 0 ]] && grn "ALL PASS\n" || { red "FAILURES\n"; exit 1; }
